services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
      - NODE_ENV=${NODE_ENV}
      - MICRO_SERVICE_HEADER=${MICRO_SERVICE_HEADER}
    depends_on:
      - mongodb
