apiVersion: v1
kind: Namespace
metadata:
  name: node-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-bot
  namespace: node-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-bot
  template:
    metadata:
      labels:
        app: nodejs-bot
    spec:
      containers:
        - name: nodejs-bot
          image: wicaksu/gateway:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: node-bot
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
