name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: wicaksu
          password: Jack03061997

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: wicaksu/gateway:wicak1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 103.132.230.120
          username: wicaksu
          password: Jack03061997
          script: |
            docker pull wicaksu/gateway:wicak1
            docker stop gateway || true
            docker rm gateway || true
            docker run -d --name gateway -p 3000:3000 --restart unless-stopped wicaksu/gateway:wicak1
